Import pycaret and data.

In [1]:
import pandas as pd
import pycaret

In [2]:
data_truth = pd.read_csv("ground_truth.csv")
data_truth.head(20)

     id                                       diagnostic  age    ges
0     1  RAQUIESTENOSIS L4-L5  Y DISCOPATIA SEVERA L5-S1   67  False
1    10                                  ABSCESO OVARICO   50  False
2   100                               Cálculo del uréter   57  False
3   101                               Cálculo del uréter   28  False
4   102                               Cálculo del uréter   54  False
5   103                               Cálculo del uréter   40  False
6   104                               Cálculo del uréter   20  False
7   105                               Cálculo del uréter   56  False
8   106                               Cálculo del uréter   74  False
9   107                               Cálculo del uréter   59  False
10  108                               Cálculo del uréter   57  False
11  109                                  CANCER DE COLON   62   True
12   11                       Absceso renal o perirrenal   62  False
13  110                                  CANCER DE COLON   78   True
14  111                                  CANCER DE COLON   84   True
15  112                                 CANCER DE OVARIO   65   True
16  113                              CANCER DE SIGMOIDES   60   True
17  114                               CANCER DE TIROIDES   39  False
18  115                       CANCER GASTRICO INCIPIENTE   58   True
19  116                               CANCER RECTO MEDIO   58   True

setup data.

In [3]:
from pycaret.classification import *
s = setup(data = data_truth, target = 'ges')

train the model.

In [7]:
best = compare_models(sort='AUC')

Tune model.

In [26]:
knn = create_model('knn')

In [34]:
print(best)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')

evaluate the model.

In [36]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

predict and save the model.

In [37]:
predict_model(best)

,id,diagnostic,age,ges,prediction_label,prediction_score
359,422,FIMOSIS,0,False,0,1.0
667,70,CA DE MAMA DERECHO,44,True,1,1.0
166,249,CBC,84,False,0,0.8
529,576,HIPERPARATIROIDISMO PRIMARIO,66,False,1,0.8
868,881,Tumor maligno de la próstata,67,True,1,0.6
...,...,...,...,...,...,...
313,381,DR OI,67,True,1,0.8
490,540,HERNIA INCISIONAL,65,False,0,1.0
833,85,CA MAMA IZQUIERDA,62,True,0,0.6
554,599,HNP LUMBAR,46,True,0,0.6
18,115,CANCER GASTRICO INCIPIENTE,58,True,1,0.8

In [41]:
new_data = data_truth.copy().drop('ges', axis=1)
predictions = predict_model(best, new_data)
predictions

,id,diagnostic,age,prediction_label,prediction_score
0,1,RAQUIESTENOSIS L4-L5 Y DISCOPATIA SEVERA L5-S1,67,0,1.0
1,10,ABSCESO OVARICO,50,0,1.0
2,100,Cálculo del uréter,57,0,1.0
3,101,Cálculo del uréter,28,0,1.0
4,102,Cálculo del uréter,54,0,1.0
...,...,...,...,...,...
936,95,Cálculo del riñón,29,0,1.0
937,96,Cálculo del riñón,73,0,0.6
938,97,Cálculo del riñón,21,0,1.0
939,98,Cálculo del uréter,51,0,1.0
940,99,Cálculo del uréter,50,0,1.0

In [42]:
save_model(best, 'ground_truth_pipeline')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None, include=['id', 'age'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean',
                                                               verbose='deprecated'))),
                 ('categorical_imputer',
                  TransformerWrapper(exclude=None, include=['diagnosti...
                                     transformer=TargetEncoder(cols=['diagnostic'],
                                                               drop_invariant=False,
                                                               handle_missing='return_nan',
                                                               handle_unknown='value',
                                                               hierarchy=None,
                                                               min_samples_leaf=20,
                                                               return_df=True,
                                                               smoothing=10,
                                                               verbose=0))),
                 ('trained_model',
                  KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                       metric='minkowski', metric_params=None,
                                       n_jobs=-1, n_neighbors=5, p=2,
                                       weights='uniform'))],
          verbose=False),
 'ground_truth_pipeline.pkl')